### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by impredicative** [FujiMakoto/IRC-Message#2]
I'm relying upon this package, but I am getting the error:

    ERROR: ircmessage 0.1.1 has requirement six<1.11,>=1.10.0, but you'll have six 1.14.0 which is incompatible.

Can the fix be published as a new release to PyPI?

**Comment by impredicative** [comment]
This is breaking my build, so it's a bit urgent.

**Comment by impredicative** [comment]
@FujiMakoto Anything?

**Comment by impredicative** [comment]
@FujiMakoto If you're done making anime bots, maybe you can do something about issue too. People actually depend on it.

**Comment by FujiMakoto** [comment]
@impredicative I'm afraid I do not work with IRC anymore and no longer have access to the PyPi account this repository was published to. You are welcome to fork and update it yourself.
